#!/bin/bash

# Install the CTC stuff
git clone --recursive https://github.com/parlance/ctcdecode.git ./deps/ctcdecode
cd ./deps/ctcdecode && pip install .

# Install the 
git clone git@github.com:SeanNaren/deepspeech.pytorch.git ./deps/deepspeech_pytorch
cd ./deps/deepspeech_pytorch && pip install .

# for development reasons
cd ./deps/deepspeech_pytorch && pip install -e . # Dev install

# As a requirement for the deepspeech_pytorch
sudo apt-get install etcd
